'''
    *  Full Name: Natalie Lewis
    *  Course: EECS 3482 A
    *  Description: Server program. Accepts connections from client programs.
    *  FOR EDUCATION PURPOSES OF ONLY. DO NOT DITSRIBUTE.
'''
import socket
import threading
import sys
import getopt
import logging
import pyfiglet
import ssl
import pickle
import os
import secrets

from Crypto.PublicKey import ECC

from lib.comms import Conn
from lib.comms import Message

# Imported Digital Signature Standard Algorithm to verify the authenticity of the client's identity
from Crypto.Signature import DSS

# Import SHA256 Hash to decode the challenge and verify the response from the client
from Crypto.Hash import SHA256

class Server:

    def __init__(self,
                 server_private_key_path,
                 server_key_password,
                 server_cert_path,
                 client_pub_key,
                 server_port):
        """        
            server_key_path: The path to the server’s private key.
            server_key_password: The password used to protect the server’s private key.
            server_cert_path: The path to the server’s certificate.
            client_pub_key: The client’s public key, used for challenge-response authentication.
            server_port: An integer representing the TCP port on which the server should listen.
        """
        logging.basicConfig(level=logging.DEBUG,
                            format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                            datefmt='%m-%d %H:%M',
                            filename='server.log',
                            filemode='w')

        console = logging.StreamHandler()
        console.setLevel(logging.INFO)
        formatter = logging.Formatter(
            '%(name)-12s: %(levelname)-8s %(message)s')
        console.setFormatter(formatter)
        logging.getLogger('').addHandler(console)

        self.server_log = logging.getLogger(self.__class__.__name__)

        # use and do not change internal variables
        self._port = server_port
        self.server_key = server_private_key_path
        self.server_key_password = server_key_password
        self.server_cert = server_cert_path
        self.client_pub_key = client_pub_key
        self.sconn = None

        # TODO: provide the correct values

        # This dictionary contains the server's certificate, the server's private key, and the password for the private key
        self.server_ssl_options = {'certfile': self.server_cert,
                                   'keyfile': self.server_key,
                                   'password': self.server_key_password}

    def get_protocol_state(self):
        """
            Return: string

            This function returns the current protocol state: 
            START, CHALLENGE, RESPONSE, SUCCESS, END, ABORT.

        """
        return self.protocol_state

    def protocol_abort(self):
        self.server_log.info('Abort protocol intiated')
        self.protocol_state = 'ABORT'
        exit(0)

    def get_new_challenge(self):
        """
         Return: string

         This function should generate a challenge (encoded as a string) to send to the client.          
        """
        # return bytes.hex(b'01'*16) # THIS IS NOT A RANDOM CHALLENGE (SECURITY WEAKNESS)
        return secrets.token_hex(16)

    def process_client_msg(self, sconn, challenge):
        """
        sconn: socket wrapper between client and server                

        Return: nothing
        """

        while True:
            """
                The input consists of two fields: type and message. 
                The type field can take on four possible values:
                CHALLENGE, RESPONSE, SUCCESS, and SESSION_MESSAGE. 

            """
            data = sconn.recv()
            
            try:
                recv_msg = pickle.loads(data)
            except:
                self.server_log.info('Connection closed')
                self.protocol_abort()

            if recv_msg['type'] == Message.RESPONSE:

                # TODO: verify the challenge response received from the client
                
                # Verify this client's signature against its own connection challenge.
                hash_challenge = SHA256.new(challenge.encode()) # Creates a SHA-256 hash to encode the challenge generated by the server
                client_public_key = ECC.import_key(open(self.client_pub_key).read()) # Imports the client's public key because the server doesn't have public access to it
                verifier = DSS.new(client_public_key, 'fips-186-3') # Creates a verifier object to verify the client's signature
                
                try:
                    verifier.verify(hash_challenge, recv_msg['msg']) # Verifies the client's signature
                    response_correct = True
                except ValueError:
                    response_correct = False

                if response_correct:
                    msg = pickle.dumps({"type": Message.SUCCESS, 'msg': ''})
                    sconn.send(msg)
                else:
                    self.protocol_state = 'ABORT'
                    self.protocol_abort()
                    break

            elif recv_msg['type'] == Message.SESSION_MESSAGE:
                # Echo messages until the client sends /quit.
                message = recv_msg['msg']
                self.server_log.info("Ping msg [%s]" % message.decode())
                msg = pickle.dumps(
                    {"type": Message.SESSION_MESSAGE, 'msg': message})
                sconn.send(msg)
                if message == b"/quit":
                    break

    def on_connect(self, sconn):
        """
         sconn: socket wrapper between client and server

         Return: nothing
        """
        challenge = self.get_new_challenge()
        # Keep each challenge local to its connection thread.
        self.server_log.info('Generated challenge: [%s] ' % challenge)
        self.protocol_state = 'CHALLENGE'

        msg = pickle.dumps({"type": Message.CHALLENGE, 'msg': challenge})
        sconn.send(msg)

        self.server_log.info('Sent challenge to client')
        self.process_client_msg(sconn, challenge)

    def server_thread(self, port):
        """
         port: server port to start a thread to accept client connection

         Return: nothing
        """

        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

        try:

            s.bind(("localhost", port))
            self.server_log.info("Listening on port %d" % port)
            s.listen(1)

            if self.server_ssl_options['certfile']:
                # Load the server identity before wrapping the listening socket.
                context.load_cert_chain(**self.server_ssl_options)
                secure_socket = context.wrap_socket(s, server_side=True)
            else:
                # when we don't have the TSL setup
                self.server_log.warning("Initiated Insecure Communication")
                secure_socket = s

            while True:
                conn, address = secure_socket.accept()
                self.server_log.info(
                    "Initiating a secure connect with %s..." % (address,))

                self.protocol_state = None

                self.sconn = Conn(conn, server=True, verbose=True)

                # Start a new thread per connection
                threading.Thread(target=self.on_connect,
                                 kwargs={'sconn': self.sconn}).start()
        except socket.error as e:
            self.server_log.info("Connection error on ort %d [%s]", port, e)

    def start(self):
        """
        starts a server thread the server listens to self._port

        Return: nothing
        """
        # Start a new thread to accept client connection
        threading.Thread(daemon=False,
                         target=self.server_thread, 
                         args=(self._port,)).start()


def main(argv):
    port = 1337
    try:
        opts, args = getopt.getopt(argv, "hp:", ["port="])
    except getopt.GetoptError:
        print('server.py -port <port>')
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print('server.py -port <port>')
            sys.exit()
        elif opt in ("-p", "--port"):
            if arg:
                port = int(arg)

    welcome_msg = pyfiglet.figlet_format(
        "Welcome to EECS 3482 A Net", font="digital")
    print(welcome_msg)

    # Resolve server certificate and key files relative to this script.
    data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
    Server(os.path.join(data_dir, "server_key.pem"), # Server private key
           None, # Private-key password
           os.path.join(data_dir, "server.pem"), # Server certificate
           os.path.join(data_dir, "client_pub_key.pem"), # Client public key
           port).start()


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except KeyboardInterrupt:
        print("\nDone!")
        exit()
